// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3Xuq2i1YKOeGauD1zkKvHNetE432GPIg',
    appId: '1:964647743537:web:26e962002f45ba568f2510',
    messagingSenderId: '964647743537',
    projectId: 'optiruta-7bf9f',
    authDomain: 'optiruta-7bf9f.firebaseapp.com',
    storageBucket: 'optiruta-7bf9f.firebasestorage.app',
    measurementId: 'G-QL1VZQ13Q9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgm3LrSeY6kFHiksyvi4A1Zlz2V45Sris',
    appId: '1:964647743537:android:bc3110f256b44d278f2510',
    messagingSenderId: '964647743537',
    projectId: 'optiruta-7bf9f',
    storageBucket: 'optiruta-7bf9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3OdI9oEAybDrkgFwLVr1TG4IutyYFEm0',
    appId: '1:964647743537:ios:b66ae857964719148f2510',
    messagingSenderId: '964647743537',
    projectId: 'optiruta-7bf9f',
    storageBucket: 'optiruta-7bf9f.firebasestorage.app',
    iosBundleId: 'com.example.optirutafinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3OdI9oEAybDrkgFwLVr1TG4IutyYFEm0',
    appId: '1:964647743537:ios:b66ae857964719148f2510',
    messagingSenderId: '964647743537',
    projectId: 'optiruta-7bf9f',
    storageBucket: 'optiruta-7bf9f.firebasestorage.app',
    iosBundleId: 'com.example.optirutafinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3Xuq2i1YKOeGauD1zkKvHNetE432GPIg',
    appId: '1:964647743537:web:53588068b82ffcf88f2510',
    messagingSenderId: '964647743537',
    projectId: 'optiruta-7bf9f',
    authDomain: 'optiruta-7bf9f.firebaseapp.com',
    storageBucket: 'optiruta-7bf9f.firebasestorage.app',
    measurementId: 'G-EY0M0SVEPE',
  );
}
